import colors

# Window Settings
WIDTH = 750
HEIGHT = 750
COLOR = colors.BLACK
FPS = 60

# Player Settings
PLAYER_WIDTH = 10
PLAYER_HEIGHT = 75
PLAYER_MARGIN = 20
PLAYER_VEL = 10
PLAYER_COLOR = colors.RED

# Ball Settings
BALL_RADIUS = 5
BALL_INIT_VEL = 5
BALL_COLOR = colors.WHITE

# Score Font Settings
SCORE_FONT_NAME = 'timesnewroman'
SCORE_FONT_SIZE = 40
SCORE_FONT_X_MARGIN = 5
SCORE_FONT_Y_MARGIN = 5
SCORE_FONT_COLOR = colors.WHITE

# Winner Font Settings
WINNER_FONT_NAME = 'timesnewroman'
WINNER_FONT_SIZE = 60
WINNER_FONT_COLOR = colors.WHITE